run-name: Build and Push CLIpedia docker image

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
    paths:
      - 'web/**'

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - uses: ncipollo/release-action@v1
      with:
        body: ${{ github.event.pull_request.body }}
        tag: clipedia-${{ steps.date.outputs.date }}-${{ github.sha }}

  docker:
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./web
          push: true
          tags: axelnemes/clipedia:${{ steps.date.outputs.date }}-${{ github.sha }}, axelnemes/clipedia:latest
          platforms: linux/arm64, linux/amd64
